spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/aacp
    username : sa
    password :
    driver-class-name: org.h2.Driver

  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        show_sql : true
        format_sql : true

logging.level:
  org.hibernate.SQL: debug
  org.springframework : debug
  org.springframework.web : debug
#  org.hibernate.type: trace
